name: example
description: A new Flutter project.
version: 1.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  # For Dio Kit
  dio: ^5.9.0
  flutter_ume: 2.0.0
  flutter_ume_kit_ui: 2.0.0
  flutter_ume_kit_perf: 2.0.0
  flutter_ume_kit_show_code: 2.0.0
  flutter_ume_kit_device: 2.0.0
  flutter_ume_kit_console: 2.0.0
  flutter_ume_kit_dio: 2.0.0

dependency_overrides:
  vm_service: ^14.0.0
  flutter_ume:
    path: ../
  flutter_ume_kit_ui:
    path: ../kits/flutter_ume_kit_ui
  flutter_ume_kit_perf:
    path: ../kits/flutter_ume_kit_perf
  flutter_ume_kit_show_code:
    path: ../kits/flutter_ume_kit_show_code
  flutter_ume_kit_device:
    path: ../kits/flutter_ume_kit_device
  flutter_ume_kit_console:
    path: ../kits/flutter_ume_kit_console
  flutter_ume_kit_dio:
    path: ../kits/flutter_ume_kit_dio
  flutter_ume_kit_channel_monitor:
    path: ../kits/flutter_ume_kit_channel_monitor

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.16.6
  
flutter:
  uses-material-design: true
