name: flutter_ume_kit_channel_monitor
description: channel monitor kit for flutter_ume
version: 2.0.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    git:
      url: https://github.com/janlionly/flutter_ume.git
      ref: master
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0 <3.0.0"
