name: flutter_ume_kit_dio
description: Dio kit for flutter_ume.
version: 2.0.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    git:
      url: https://github.com/janlionly/flutter_ume.git
      ref: master

  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65
